site_name: jaxquantum
site_url: https://jaxquantum.org
use_directory_urls: false
repo_url: https://github.com/EQuS/jaxquantum
repo_name: jaxquantum

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - content.code.copy
  logo: assets/logo.png
  favicon: assets/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: purple
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
copyright: "&copy Copyright 2022-2025, JAXquantum developers."
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/EQuS/jaxquantum
plugins:
  - search
  - mkdocs-jupyter:
      execute: true
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py
  - literate-nav:
      nav_file: summary.md
  - section-index
  - mkdocstrings:
      watch:
      - docs
      - jaxquantum
markdown_extensions:
  - toc
  - admonition
  - codehilite
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets

nav:
  - About: 
    - index.md
    - Community: about/community.md
    - Contributors: about/contributors.md
    - Citation: about/citation.md
  - Documentation:
    - documentation/index.md
    - Getting started:
      - Installation: documentation/getting_started/installation.md
      - Qarray: documentation/getting_started/qarray.ipynb
      # - Examples: getting_started/examples.md
      - The Sharp Bits 🔪: documentation/getting_started/sharp_bits.md
    - Tutorials:
      - Bosonic Codes: documentation/tutorials/bosonic_codes.md
    - Advanced Concepts:
      - Excitation Number Restricted Basis: documentation/advanced/enr.md
  - Code Reference: reference/