name: tests
on:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[tests]"
      - name: Test with pytest
        run: |
          pytest ./test --doctest-modules --junitxml=junit/test-results.xml --cov=jaxquantum --cov-report=xml --cov-report=html:cov_html
      - name: Move files
        run: |
          mkdir test-results
          mv junit/test-results.xml ./test-results
          mv ./coverage.xml ./test-results
          mv ./cov_html ./test-results
          rm ./test-results/cov_html/.gitignore
          cd ./test-results
          
      - name: Coverage Bagdge
        uses: tj-actions/coverage-badge-py@v1.8
        with:
          output: test-results/coverage.svg
      - name: Deploy badge to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          clean: false
          folder: test-results
          target-folder: test-results
