name: Pytest
on: [ push, pull_request ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest ./test --doctest-modules --junitxml=junit/test-results.xml --cov=jaxquantum --cov-report=xml --cov-report=html:cov_html
      - name: Move files
        run: |
          mkdir test-results
          mv junit/test-results.xml ./test-results
          mv ./coverage.xml ./test-results
          mv ./cov_html ./test-results/
          cd ./test-results
      - name: Coverage Bagdge
        uses: tj-actions/coverage-badge-py@v1.8
        with:
          output: test-results/coverage.svg
      - name: Deploy badge to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: test-results
          folder: test-results
