name: Pytest
on: [ push, pull_request ]
jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest ./test --doctest-modules --junitxml=junit/test-results.xml --cov=jaxquantum --cov-report=xml --cov-report=html
      - name: 'Upload pytest results'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: junit/test-results.xml
      - name: 'Upload coverage results'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-results
          path: coverage.xml
      - name: Coverage Bagdge
        uses: tj-actions/coverage-badge-py@v1.8
        with:
          output: coverage.svg
      - name: Deploy badge to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: test-results
